# Site settings
title: "AWS Cli Wiki"
bye_message: "*ss*"
baseurl: "/aws-cli-wiki/"
url: "https://Rajchowdhury420.github.io"
disqus: Rajchowdhury420

# Header settings
Raj: "Rajchowdhury420"
source_code:
    server: "github.com"
    Raj: "RajChowdhury420"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
